name: deepar
description: A new Flutter plugin project.
version: 0.0.1
homepage:

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  deepar_android: 
    path: ../deepar_android
  deepar_ios: 
    path: ../deepar_ios
  deepar_web: 
    path: ../deepar_web
  deepar_macos: 
    path: ../deepar_macos            

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter: 
  plugin:
    platforms: 
      android:
        default_package: deepar_android
      ios:
        default_package: deepar_ios
      macos:
        default_package: deepar_macos
      web:
        default_package: deepar_web      
                    